version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  commit-message:
    prefix: "actions-update"
  labels: [ 'enhancement' ]
  schedule:
    interval: "daily"
  groups:
    actions-dependencies:
      applies-to: version-updates
      patterns:
      - "*"
- package-ecosystem: "gradle"
  directory: "/"
  commit-message:
    prefix: "gradle-update"
  labels: [ 'enhancement' ]
  schedule:
    interval: "daily"
  ignore:
  - dependency-name: "*"
    update-types: [ "version-update:semver-major" ]
  groups:
    gradle-dependencies:
      applies-to: version-updates
      patterns:
      - "*"
